namespace MyCompiler.Core.Enums
{
    public enum LexicAnalyserState
    {
        Initial,
        NonTerminal,
        Space,
        Terminal,
        Empty,
        Identifier,
        Number,
        NewLine,
        Write,
        Read,
        If,
        End,
        Then,
        Begin,
        Do,
        SemiColon,
        While,
        Var,
        OpenParentheses,
        CloseParentheses,
        Plus,
        Sub,
        Great,
        Less,
        Equal,
        Repeat,
        Until,
        Attribution,
        NotEqual,
        GreatOrEqual,
        LessOrEqual
    }
}